version: "3"

services:
  # React App
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    env_file:
      - ./client/.env

  # ExpressJS API
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
